import { useEffect, useRef } from "react";
import { gsap } from "gsap";
import LazyImage from "./LazyImage.jsx";

export default function About({ preview = false, reviews = [], onSubmitReview, onNavigate }) {
  const sectionRef = useRef(null);

  useEffect(() => {
    if (preview || !sectionRef.current) return undefined;

    const elements = sectionRef.current.querySelectorAll(".about-image, .about-copy > *, .about-facts > div, .about-contact");
    gsap.fromTo(elements, { opacity: 0, y: 24 }, { opacity: 1, y: 0, duration: 0.7, stagger: 0.08, ease: "power2.out" });

    return () => gsap.killTweensOf(elements);
  }, [preview]);

  if (preview) {
    return <section ref={sectionRef} className="mx-auto grid max-w-7xl items-center gap-9 px-5 py-16 sm:px-8 md:grid-cols-[1fr_.9fr] md:py-24"><div className="about-image min-w-0"><LazyImage src="/images/pink-flower-bag.webp" alt="Handmade pink flower shoulder bag" aspect="aspect-[4/3]" className="min-h-[300px] bg-[#d9c5b9] md:min-h-[460px]" /></div><div className="about-copy min-w-0"><p className="eyebrow">The Yarnify story</p><h2 className="type-display-lg">Made for <em className="text-clay">soft</em><br />moments.</h2><p className="type-body mt-6 max-w-[420px] text-ink/60">Thoughtful crochet pieces for bright homes, slow mornings, and the people you love.</p><button type="button" className="text-link mt-4 inline-block border-0 bg-transparent p-0" onClick={() => onNavigate("/about")}>Meet the maker ↗</button></div></section>;
  }

  const displayedReviews = reviews;

  return (
    <main ref={sectionRef} className="about-page bg-[#f7f6f3]">
      <section className="about-intro mx-auto grid max-w-7xl gap-8 px-5 py-12 sm:px-8 md:grid-cols-[1.05fr_.95fr] md:items-end md:py-20">
        <div className="about-copy"><p className="eyebrow">About Yarnify / handmade studio</p><h1 className="type-display-xl">A little more<br /><em className="text-clay">human.</em></h1><p className="type-body mt-7 max-w-[470px] text-ink/65">Useful, joyful crochet objects made slowly for bright homes, soft mornings, and the people you love.</p></div>
        <div className="about-image editorial-frame"><LazyImage src="/images/pink-rose-blanket.webp" alt="Handmade pink rose crochet blanket" aspect="aspect-[4/3]" /></div>
      </section>
      <section className="about-stats bg-cream px-5 py-12 sm:px-8 md:py-16"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-3"><div><strong className="font-display text-5xl text-clay">01</strong><p className="mt-3 font-mono text-[10px] uppercase tracking-[.12em] text-ink/60">Made by hand</p></div><div><strong className="font-display text-5xl text-clay">02</strong><p className="mt-3 font-mono text-[10px] uppercase tracking-[.12em] text-ink/60">Small batch always</p></div><div><strong className="font-display text-5xl text-clay">03</strong><p className="mt-3 font-mono text-[10px] uppercase tracking-[.12em] text-ink/60">Meant to be kept</p></div></div></section>
      <section className="about-faq mx-auto max-w-4xl px-5 py-16 sm:px-8 md:py-20"><div className="mb-8"><p className="eyebrow">Good to know</p><h2 className="type-display-md">Frequently asked<br /><em className="text-clay">questions.</em></h2></div><div className="faq-list"><details open><summary>Are the pieces handmade?</summary><p>Yes. Every Yarnify piece is made by hand in small batches, so small variations are part of its character.</p></details><details><summary>How can I ask about an order?</summary><p>Use the Contact page to email us or message us through Instagram, TikTok, or YouTube.</p></details><details><summary>Can I request a custom piece?</summary><p>Send us a note with the colors, shape, and kind of piece you have in mind, and we will let you know what is possible.</p></details><details><summary>How do I care for crochet?</summary><p>Keep handmade pieces away from rough surfaces and wash gently according to the care guidance shared with your order.</p></details></div></section>
      <section className="about-reviews mx-auto max-w-7xl px-5 py-16 sm:px-8 md:py-24"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Words from the Yarnify circle</p><h2 className="type-display-lg">Made with care,<br /><em className="text-clay">felt at home.</em></h2></div><p className="max-w-[270px] text-sm leading-7 text-ink/55">{reviews.length ? "Notes from people who have made room for Yarnify in their everyday." : "No reviews yet. Be the first to share your experience."}</p></div>{reviews.length > 0 && <div className="review-wall">{displayedReviews.map((review, index) => <article key={`${review.name}-${index}`} className="review-card"><div className="text-sm tracking-[.16em] text-clay">{"★".repeat(review.rating)}</div><p className="mt-5 text-sm leading-7 text-ink/70">“{review.comment}”</p><div className="mt-6 border-t border-line pt-4"><strong className="text-sm">{review.name}</strong><p className="mt-1 font-mono text-[9px] uppercase tracking-[.1em] text-ink/45">Yarnify customer</p></div></article>)}</div>}<form className="review-form mx-auto mt-12 grid max-w-2xl gap-4 border border-line bg-cream p-6 sm:p-8" onSubmit={onSubmitReview}><p className="font-mono text-[10px] uppercase tracking-[.12em] text-clay">Leave a review</p><label className="grid gap-1 text-xs text-ink/60">Name<input name="name" required maxLength="50" className="border-b border-line bg-transparent px-0 py-3 text-sm text-ink outline-none focus:border-clay" placeholder="Your name" /></label><label className="grid gap-1 text-xs text-ink/60">Rating<select name="rating" className="border-b border-line bg-cream px-0 py-3 text-sm text-ink outline-none focus:border-clay" defaultValue="5"><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select></label><label className="grid gap-1 text-xs text-ink/60">Comment<textarea name="comment" required maxLength="240" className="min-h-24 resize-y border-b border-line bg-transparent px-0 py-3 text-sm text-ink outline-none focus:border-clay" placeholder="Tell us what you think" /></label><button className="button-dark mt-3 w-fit" type="submit">Give review <span>↗</span></button></form></section>
      <section className="about-subscribe bg-coral px-5 py-14 text-[#fff4ed] sm:px-8 md:py-20"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="mb-4 font-mono text-[10px] uppercase tracking-[.14em] text-[#ffd4c6]">Follow Yarnify</p><h2 className="type-display-lg">Watch the<br /><em>latest makes.</em></h2></div><a className="inline-flex min-h-14 items-center gap-6 bg-cream px-6 text-xs font-semibold text-ink transition hover:bg-ink hover:text-cream" href="https://www.youtube.com/@yarnify988" target="_blank" rel="noreferrer">Visit our YouTube <span>↗</span></a></div></section>
      <section id="contact" className="about-contact bg-ink px-5 py-14 text-cream sm:px-8 md:py-20"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="mb-4 font-mono text-[10px] uppercase tracking-[.14em] text-coral">Find Yarnify online</p><h2 className="type-display-md">Stay in the loop.</h2></div><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm text-cream/75"><a href="mailto:binte.shahid789@gmail.com" className="hover:text-coral">✉ Email</a><a href="https://www.instagram.com/rida_cr0chet988" target="_blank" rel="noreferrer" className="hover:text-coral">◎ Instagram @rida_cr0chet988</a><a href="https://www.tiktok.com/@rida_crochet988" target="_blank" rel="noreferrer" className="hover:text-coral">♪ TikTok @rida_crochet988</a><a href="https://www.youtube.com/@yarnify988" target="_blank" rel="noreferrer" className="hover:text-coral">▶ YouTube ↗</a></div></div></section>
    </main>
  );
}
